name: Code Duplication Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Manuel olarak çalıştırılabilmesi için
  workflow_dispatch:

jobs:
  check-duplicates:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install jscpd
        run: npm install -g jscpd
        
      - name: Run duplication check
        run: |
          jscpd ./src \
            --ignore "**/*.test.js,**/*.spec.js,node_modules/**,dist/**,build/**" \
            --reporters html,json,console \
            --format "javascript,typescript,jsx,tsx,css,scss" \
            --output ./jscpd-report \
            --threshold 1
            
      - name: Upload report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jscpd-report
          path: ./jscpd-report
          
      # İsteğe bağlı: Belirli bir eşiği aşan duplikasyonları hata olarak işaretleme
      - name: Check duplication threshold
        run: |
          if [ -f ./jscpd-report/jscpd-report.json ]; then
            DUPLICATION=$(jq '.statistics.total.percentage' ./jscpd-report/jscpd-report.json)
            if (( $(echo "$DUPLICATION > 5" | bc -l) )); then
              echo "Duplication percentage ($DUPLICATION%) is above threshold (5%)"
              exit 1
            fi
          fi
