name: jscpd PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  jscpd-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update main branch (Critical!)
        run: git fetch origin main && git checkout main

      - name: Set base branch for comparison
        run: |
          BASE_BRANCH=$(git merge-base origin/main HEAD)
          echo "BASE_BRANCH: $BASE_BRANCH"
          FULL_SHA=$(git rev-parse HEAD)
          echo "FULL_SHA: $FULL_SHA"

      - name: Get changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff -w --name-only $BASE_BRANCH HEAD | grep -E '\.js|\.ts|\.py|\.java|\.go|\.php|\.c|\.cpp|\.cs' || true) # -w added
          echo "CHANGED_FILES: $CHANGED_FILES"
          if [ -z "$CHANGED_FILES" ]; then
            echo "No relevant files changed."
            exit 0
          fi

      - name: Run jscpd only on changed files
        if: env.CHANGED_FILES != ''
        run: jscpd --min-tokens 50 --reporters json --files ${{ env.CHANGED_FILES }}

      - name: Check for report.json and upload
        if: env.CHANGED_FILES != ''
        run: |
          if [[ -f report.json ]]; then
            echo "Uploading jscpd report..."
            uses: actions/upload-artifact@v3
            with:
              name: jscpd-report
              path: report.json
          else
            echo "No jscpd report generated (likely no duplication found)."
          fi
