name: Reusable jscpd Workflow

on:
  workflow_call:
    inputs:
      base_branch:
        required: false
        default: "main"
        type: string

jobs:
  jscpd-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch full history
        run: git fetch --prune --unshallow || true

      - name: Install jscpd
        run: npm install -g jscpd

      - name: Get changed files
        id: changed-files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only origin/${{ inputs.base_branch }} | grep -E '\.js|\.ts|\.py|\.java|\.go|\.php|\.c|\.cpp|\.cs' | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Run jscpd only on changed files
        if: env.CHANGED_FILES != ''
        run: jscpd --min-tokens 50 --reporters json --files ${{ env.CHANGED_FILES }}

      - name: Upload jscpd report
        uses: actions/upload-artifact@v3
        with:
          name: jscpd-report
          path: report.json
