name: jscpd PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  jscpd-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set base branch for comparison
        run: echo "BASE_BRANCH=$(git merge-base origin/main HEAD)" >> $GITHUB_ENV

      - name: Install jscpd
        run: npm install -g jscpd jq

      - name: Get changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only $BASE_BRANCH HEAD | grep -Ei '\.(js|ts|py|java|go|php|c|cpp|cs)$' || true)
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No relevant files changed."
            exit 0
          fi

      - name: Run jscpd and generate reports
        if: env.CHANGED_FILES != ''
        run: |
          mkdir -p jscpd-reports
          jscpd --min-tokens 50 --reporters json,html --output-dir ./jscpd-reports || true
          
          # JSON rapordan yüzdeyi çek
          DUPLICATION_PERCENTAGE=$(jq '.percentage' jscpd-reports/jscpd-report.json)
          echo "Duplication Percentage: $DUPLICATION_PERCENTAGE"

          # Eğer yüzde 25'in üzerindeyse hata ver ve PR'de decorator (annotation) ekle
          if (( $(echo "$DUPLICATION_PERCENTAGE > 25" | bc -l) )); then
            echo "::error title=High Code Duplication::Code duplication exceeded threshold ($DUPLICATION_PERCENTAGE% > 25%)"
            exit 1
          fi

      - name: Generate GitHub PR Annotations (Decorators)
        if: failure()
        run: |
          jq -c '.duplicates[]' jscpd-reports/jscpd-report.json | while read line; do
            FILE=$(echo "$line" | jq -r '.firstFile')
            START_LINE=$(echo "$line" | jq -r '.firstStartLine')
            END_LINE=$(echo "$line" | jq -r '.firstEndLine')
            echo "::error file=$FILE,line=$START_LINE,endLine=$END_LINE,title=Duplicate Code Detected::Code is duplicated in multiple locations."
          done

      - name: Upload Reports
        if: env.CHANGED_FILES != ''
        uses: actions/upload-artifact@v3
        with:
          name: jscpd-reports
          path: jscpd-reports/
