name: Code Duplication Check

on:
  pull_request:
    branches:
      - main  # Or your main branch name

jobs:
  jscpd-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Retrieve full Git history

      - name: Set Base Branch
        id: set-base-branch
        run: |
          BASE_BRANCH=$(git merge-base origin/main HEAD)
          echo "BASE_BRANCH=$BASE_BRANCH" >> $GITHUB_ENV

      - name: Install jscpd
        run: npm install -g jscpd

      - name: Get Changed Files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only $BASE_BRANCH HEAD | grep -Ei '\.(js|ts|py|java|go|php|c|cpp|cs|jsx|tsx|html|css|scss|less|json|xml|yaml|yml|sql|sh|bash|md|txt)$' || true)
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

          # Debugging Steps (Essential)
          echo "Debug: BASE_BRANCH: $(git merge-base origin/main HEAD)"
          echo "Debug: HEAD: $(git rev-parse HEAD)"
          ls -l  # List all files in the workspace
          echo "Debug: grep command: grep -Ei '\.(js|ts|...|txt)$'"
          echo "Debug: CHANGED_FILES: ${{ env.CHANGED_FILES }}"

          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No relevant files changed."
            exit 0
          fi

      - name: Run jscpd
        if: env.CHANGED_FILES != ''
        run: |
          mkdir jscpd-reports # Make the directory explicitly
          jscpd --min-tokens 50 --reporters json,html --output-dir ./jscpd-reports ${{ env.CHANGED_FILES }} || exit 1

          # Display jscpd output (Optional, but very useful for quick feedback)
          echo "jscpd JSON Report:"
          cat jscpd-reports/report.json || true # Handle potential file absence
          echo "----------------------------------------"
          echo "jscpd HTML Report:"
          cat jscpd-reports/report.html || true # Handle potential file absence

      - name: Upload Reports
        if: env.CHANGED_FILES != ''
        run: |
          if [[ -f jscpd-reports/report.json ]]; then
            uses: actions/upload-artifact@v3
            with:
              name: jscpd-report
              path: jscpd-reports/report.json
          fi

          if [[ -f jscpd-reports/report.html ]]; then
            uses: actions/upload-artifact@v3
            with:
              name: jscpd-html-report
              path: jscpd-reports/report.html
          fi
