name: Reusable jscpd Workflow

on:
  workflow_call:
    inputs:
      base_branch:
        required: false
        default: "main"
        type: string

jobs:
  jscpd-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Tüm commit geçmişini al

      - name: Install jscpd
        run: npm install -g jscpd

      - name: Get changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ inputs.base_branch }} | grep -E '\.js|\.ts|\.py|\.java|\.go|\.php|\.c|\.cpp|\.cs' | tr '\n' ' ')
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "::set-output name=files::$CHANGED_FILES"

      - name: Run jscpd only on changed files
        if: steps.changed-files.outputs.files != ''
        run: jscpd --min-tokens 50 --reporters json --files ${{ steps.changed-files.outputs.files }}

      - name: Upload jscpd report
        uses: actions/upload-artifact@v3
        with:
          name: jscpd-report
          path: report.json
