name: jscpd PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  jscpd-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ Updated to v4

      - name: Install jscpd & jq
        run: npm install -g jscpd jq

      - name: Set base branch for comparison
        run: echo "BASE_BRANCH=$(git merge-base origin/main HEAD)" >> $GITHUB_ENV

      - name: Get changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only $BASE_BRANCH HEAD | grep -Ei '\.(js|ts|py|java|go|php|c|cpp|cs)$' || true)
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No relevant files changed."
            exit 0
          fi

      - name: Run jscpd and generate reports
        if: env.CHANGED_FILES != ''
        run: |
          mkdir -p jscpd-reports
          jscpd --min-tokens 50 --reporters json,html --output ./jscpd-reports || true
          
          # Extract duplication percentage from JSON report
          DUPLICATION_PERCENTAGE=$(jq '.percentage' jscpd-reports/jscpd-report.json)
          echo "Duplication Percentage: $DUPLICATION_PERCENTAGE" >> $GITHUB_ENV

          # If duplication exceeds 25%, fail the step
          if (( $(echo "$DUPLICATION_PERCENTAGE > 25" | bc -l) )); then
            echo "::error title=High Code Duplication::Code duplication exceeded threshold ($DUPLICATION_PERCENTA
