name: Kod Tekrarı Kontrolü

on:
  pull_request:
    branches:
      - main  # veya ana dalınızın adı

jobs:
  jscpd-kontrol:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Kontrol Et
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Tam geçmiş için

      - name: jscpd Kurulumu
        run: npm install -g jscpd

      - name: Değişen Dosyaları Al
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only $BASE_BRANCH HEAD | grep -Ei '\.(js|ts|py|java|go|php|c|cpp|cs|jsx|tsx|html|css|scss|less|json|xml|yaml|yml|sql|sh|bash|md|txt)$' || true)
          echo "DEĞİŞEN_DOSYALAR=$CHANGED_FILES" >> $GITHUB_ENV

          # Hata ayıklama adımları (önerilir)
          echo "Debug: BASE_BRANCH: $(git merge-base origin/main HEAD)"
          echo "Debug: HEAD: $(git rev-parse HEAD)"
          ls -l  # Tüm dosyaları listele
          echo "Debug: grep komutu: grep -Ei '\.(js|ts|...|txt)$' | grep -v '^$'"
          echo "Debug: DEĞİŞEN_DOSYALAR: ${{ env.CHANGED_FILES }}"

          if [ -z "$CHANGED_FILES" ]; then
            echo "Değişen dosya bulunamadı."
            exit 0
          fi

      - name: jscpd Çalıştır
        if: env.CHANGED_FILES != ''
        run: jscpd --min-tokens 50 --reporters json,html ${{ env.CHANGED_FILES }} || exit 1 # JSON ve HTML raporları

      - name: Raporları Kontrol Et ve Yükle
        if: env.CHANGED_FILES != ''
        run: |
          if [[ -f report.json ]]; then
            echo "jscpd raporu bulundu. Yükleniyor..."
            uses: actions/upload-artifact@v3
            with:
              name: jscpd-raporu
              path: report.json
          else
            echo "jscpd raporu bulunamadı (muhtemelen tekrar eden kod yok)."
          fi

          if [[ -f report.html ]]; then
            echo "jscpd HTML raporu bulundu. Yükleniyor..."
            uses: actions/upload-artifact@v3
            with:
              name: jscpd-html-raporu
              path: report.html
          else
            echo "jscpd HTML raporu bulunamadı."
          fi
