name: PMD Code Smells Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pmd-analysis:
    runs-on: ubuntu-latest
    steps:
      # Kodları checkout yap
      - name: Checkout code
        uses: actions/checkout@v4

      # Java ortamını kur (PMD için gerekli)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # PMD’yi indir, unzip et ve çalıştır
      - name: Download and Run PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.10.0/pmd-dist-7.10.0-bin.zip
          unzip pmd-dist-7.10.0-bin.zip
          chmod +x pmd-bin-7.10.0/bin/pmd
          ./pmd-bin-7.10.0/bin/pmd check -d . -R rulesets/java/codesize.xml,rulesets/java/design.xml -f sarif -r pmd-report.sarif

      # SARIF sonuçlarını GitHub Code Scanning’e yükle
      - name: Upload PMD Report
        if: always()  # Hata olsa bile rapor yüklenmesini sağlar
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pmd-report.sarif
